object Versions {
  lazy val akkaVersion                 = "2.6.16"
  lazy val akkaHttpVersion             = "10.2.6"
  lazy val awsSdkVersion               = "2.4.17"
  lazy val projectionVersion           = "1.2.1"
  lazy val cassandraPersistenceVersion = "1.0.5"
  lazy val jdbcPersistenceVersion      = "5.0.1"
  lazy val slickVersion                = "3.3.3"
  lazy val s3Persistence               = "1.0.27"
  lazy val httpJson4sVersion           = "1.38.2"
  lazy val akkaManagementVersion       = "1.0.10"
  lazy val json4sVersion               = "4.0.3"
  lazy val mustacheVersion             = "0.9.0"
  lazy val kamonVersion                = "2.2.0"
  lazy val openapi4jVersion            = "1.0.7"
  lazy val resilience4jVersion         = "1.7.1"
  lazy val scalapbVersion              = "0.11.1"
  lazy val jacksonVersion              = "2.11.4"
  lazy val commonsFileUploadVersion    = "1.4"
  lazy val logbackVersion              = "1.2.3"
  lazy val scalatestVersion            = "3.2.8"
  lazy val mockitoVersion              = "3.9.0"
}
